version: '3'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: .env

  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - dev-db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  dev-db: