version: '3'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ..:/code
    networks:
      - backend-network
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

networks:
  backend-network:
    driver: bridge

volumes:
  dev-db-data: