version: '3'

services:
  backend:
    container_name: backend
    build: .
    command: uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ..:/code
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge