version: '3'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:fastapi_app --host 0.0.0.0 --port ${APP_PORT} --reload"
    working_dir: /app

  db:
    container_name: "db"
    image: postgres:14.1-alpine
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - dev-db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  dev-db: